module.exports = {
  apps: [
    {
      name: 'api',
      script: 'src/index.ts',
      interpreter: 'bun',
      watch: false,
      autorestart: true,
      max_memory_restart: '512M',
      exp_backoff_restart_delay: 100,
      merge_logs: true,
      log_type: 'json',
      env: { PM2_APP_NAME: 'api' },
    },
    {
      name: 'worker-gate',
      script: 'src/workers/gateWorker.ts',
      interpreter: 'bun',
      watch: false,
      autorestart: true,
      max_memory_restart: '512M',
      exp_backoff_restart_delay: 100,
      merge_logs: true,
      log_type: 'json',
      env: { PM2_APP_NAME: 'worker-gate' },
    },
    {
      name: 'worker-okx',
      script: 'src/workers/okxWorker.ts',
      interpreter: 'bun',
      watch: false,
      autorestart: true,
      max_memory_restart: '512M',
      exp_backoff_restart_delay: 100,
      merge_logs: true,
      log_type: 'json',
      env: { PM2_APP_NAME: 'worker-okx' },
    },
    {
      name: 'worker-hyperliquid',
      script: 'src/workers/hyperliquidWorker.ts',
      interpreter: 'bun',
      watch: false,
      autorestart: true,
      max_memory_restart: '512M',
      exp_backoff_restart_delay: 100,
      merge_logs: true,
      log_type: 'json',
      env: { PM2_APP_NAME: 'worker-hyperliquid' },
    },
    {
      name: 'worker-tokocrypto',
      script: 'src/workers/tokocryptoWorker.ts',
      interpreter: 'bun',
      watch: false,
      autorestart: true,
      max_memory_restart: '512M',
      exp_backoff_restart_delay: 100,
      merge_logs: true,
      log_type: 'json',
      env: { PM2_APP_NAME: 'worker-tokocrypto' },
    },
    {
      name: 'worker-bitget',
      script: 'src/workers/bitgetWorker.ts',
      interpreter: 'bun',
      watch: false,
      autorestart: true,
      max_memory_restart: '512M',
      exp_backoff_restart_delay: 100,
      merge_logs: true,
      log_type: 'json',
      env: { PM2_APP_NAME: 'worker-bitget' },
    },
    {
      name: 'worker-mexc',
      script: 'src/workers/mexcWorker.ts',
      interpreter: 'bun',
      watch: false,
      autorestart: true,
      max_memory_restart: '512M',
      exp_backoff_restart_delay: 100,
      merge_logs: true,
      log_type: 'json',
      env: { PM2_APP_NAME: 'worker-mexc' },
    },
    {
      name: 'worker-bitmart',
      script: 'src/workers/bitmartWorker.ts',
      interpreter: 'bun',
      watch: false,
      autorestart: true,
      max_memory_restart: '512M',
      exp_backoff_restart_delay: 100,
      merge_logs: true,
      log_type: 'json',
      env: { PM2_APP_NAME: 'worker-bitmart' },
    },
    {
      name: 'reconcile-cron',
      script: 'src/workers/reconcileCron.ts',
      interpreter: 'bun',
      watch: false,
      autorestart: true,
      max_memory_restart: '256M',
      exp_backoff_restart_delay: 100,
      merge_logs: true,
      log_type: 'json',
      env: { PM2_APP_NAME: 'reconcile-cron' },
    },
  ],
};
