module.exports = {
  apps: [
    {
      name: 'api',
      script: 'src/index.ts',
      interpreter: 'bun',
      watch: false,
      autorestart: true,
      max_memory_restart: '512M',
      exp_backoff_restart_delay: 100,
    },
    {
      name: 'worker-gate',
      script: 'src/workers/gateWorkerRunner.ts',
      interpreter: 'bun',
      watch: false,
      autorestart: true,
      max_memory_restart: '512M',
      exp_backoff_restart_delay: 100,
    },
    {
      name: 'worker-okx',
      script: 'src/workers/okxWorkerRunner.ts',
      interpreter: 'bun',
      watch: false,
      autorestart: true,
      max_memory_restart: '512M',
      exp_backoff_restart_delay: 100,
    },
    {
      name: 'worker-hyperliquid',
      script: 'src/workers/hyperliquidWorkerRunner.ts',
      interpreter: 'bun',
      watch: false,
      autorestart: true,
      max_memory_restart: '512M',
      exp_backoff_restart_delay: 100,
    },
    {
      name: 'worker-tokocrypto',
      script: 'src/workers/tokocryptoWorkerRunner.ts',
      interpreter: 'bun',
      watch: false,
      autorestart: true,
      max_memory_restart: '512M',
      exp_backoff_restart_delay: 100,
    },
  ],
};
