module.exports = {
  apps: [
    {
      name: 'api',
      script: 'src/index.ts',
      interpreter: 'bun',
      watch: false,
      autorestart: true,
      max_memory_restart: '512M',
      exp_backoff_restart_delay: 100,
    },
    {
      name: 'worker-gate',
      script: 'src/workers/gateWorker.ts',
      interpreter: 'bun',
      watch: false,
      autorestart: true,
      max_memory_restart: '512M',
      exp_backoff_restart_delay: 100,
    },
    {
      name: 'worker-okx',
      script: 'src/workers/okxWorker.ts',
      interpreter: 'bun',
      watch: false,
      autorestart: true,
      max_memory_restart: '512M',
      exp_backoff_restart_delay: 100,
    },
    {
      name: 'worker-hyperliquid',
      script: 'src/workers/hyperliquidWorker.ts',
      interpreter: 'bun',
      watch: false,
      autorestart: true,
      max_memory_restart: '512M',
      exp_backoff_restart_delay: 100,
    },
    {
      name: 'worker-tokocrypto',
      script: 'src/workers/tokocryptoWorker.ts',
      interpreter: 'bun',
      watch: false,
      autorestart: true,
      max_memory_residual: '512M',
      exp_backoff_restart_delay: 100,
    },
    {
      name: 'worker-bitget',
      script: 'src/workers/bitgetWorker.ts',
      interpreter: 'bun',
      watch: false,
      autorestart: true,
      max_memory_restart: '512M',
      exp_backoff_restart_delay: 100,
    },
    {
      name: 'worker-mexc',
      script: 'src/workers/mexcWorker.ts',
      interpreter: 'bun',
      watch: false,
      autorestart: true,
      max_memory_restart: '512M',
      exp_backoff_restart_delay: 100,
    },
    {
      name: 'worker-bitmart',
      script: 'src/workers/bitmartWorker.ts',
      interpreter: 'bun',
      watch: false,
      autorestart: true,
      max_memory_restart: '512M',
      exp_backoff_restart_delay: 100,
    },
    {
      name: 'reconcile-cron',
      script: 'src/workers/reconcileCron.ts',
      interpreter: 'bun',
      watch: false,
      autorestart: true,
      max_memory_restart: '256M',
      exp_backoff_restart_delay: 100,
    },
  ],
};
